insert into teams (name, code, group_name, flag_emoji) values
  ('Czechia', 'CZE', 'A', '🇨🇿'),
  ('Mexico', 'MEX', 'A', '🇲🇽'),
  ('South Africa', 'RSA', 'A', '🇿🇦'),
  ('South Korea', 'KOR', 'A', '🇰🇷'),
  ('Bosnia-Herzegovina', 'BIH', 'B', '🇧🇦'),
  ('Canada', 'CAN', 'B', '🇨🇦'),
  ('Qatar', 'QAT', 'B', '🇶🇦'),
  ('Switzerland', 'SUI', 'B', '🇨🇭'),
  ('Brazil', 'BRA', 'C', '🇧🇷'),
  ('Haiti', 'HAI', 'C', '🇭🇹'),
  ('Morocco', 'MAR', 'C', '🇲🇦'),
  ('Scotland', 'SCO', 'C', '🏴󠁧󠁢󠁳󠁣󠁴󠁿'),
  ('Australia', 'AUS', 'D', '🇦🇺'),
  ('Paraguay', 'PAR', 'D', '🇵🇾'),
  ('Turkey', 'TUR', 'D', '🇹🇷'),
  ('United States', 'USA', 'D', '🇺🇸'),
  ('Curaçao', 'CUW', 'E', '🇨🇼'),
  ('Ecuador', 'ECU', 'E', '🇪🇨'),
  ('Germany', 'GER', 'E', '🇩🇪'),
  ('Ivory Coast', 'CIV', 'E', '🇨🇮'),
  ('Japan', 'JPN', 'F', '🇯🇵'),
  ('Netherlands', 'NED', 'F', '🇳🇱'),
  ('Sweden', 'SWE', 'F', '🇸🇪'),
  ('Tunisia', 'TUN', 'F', '🇹🇳'),
  ('Belgium', 'BEL', 'G', '🇧🇪'),
  ('Egypt', 'EGY', 'G', '🇪🇬'),
  ('Iran', 'IRN', 'G', '🇮🇷'),
  ('New Zealand', 'NZL', 'G', '🇳🇿'),
  ('Cape Verde Islands', 'CPV', 'H', '🇨🇻'),
  ('Saudi Arabia', 'KSA', 'H', '🇸🇦'),
  ('Spain', 'ESP', 'H', '🇪🇸'),
  ('Uruguay', 'URY', 'H', '🇺🇾'),
  ('France', 'FRA', 'I', '🇫🇷'),
  ('Iraq', 'IRQ', 'I', '🇮🇶'),
  ('Norway', 'NOR', 'I', '🇳🇴'),
  ('Senegal', 'SEN', 'I', '🇸🇳'),
  ('Algeria', 'ALG', 'J', '🇩🇿'),
  ('Argentina', 'ARG', 'J', '🇦🇷'),
  ('Austria', 'AUT', 'J', '🇦🇹'),
  ('Jordan', 'JOR', 'J', '🇯🇴'),
  ('Colombia', 'COL', 'K', '🇨🇴'),
  ('Congo DR', 'COD', 'K', '🇨🇩'),
  ('Portugal', 'POR', 'K', '🇵🇹'),
  ('Uzbekistan', 'UZB', 'K', '🇺🇿'),
  ('Croatia', 'CRO', 'L', '🇭🇷'),
  ('England', 'ENG', 'L', '🏴󠁧󠁢󠁥󠁮󠁧󠁿'),
  ('Ghana', 'GHA', 'L', '🇬🇭'),
  ('Panama', 'PAN', 'L', '🇵🇦');
