insert into teams (name, code, group_name, flag_emoji) values
  ('United States', 'USA', 'A', '🇺🇸'),
  ('Panama', 'PAN', 'A', '🇵🇦'),
  ('Honduras', 'HON', 'A', '🇭🇳'),
  ('Jamaica', 'JAM', 'A', '🇯🇲'),
  ('Argentina', 'ARG', 'B', '🇦🇷'),
  ('Chile', 'CHI', 'B', '🇨🇱'),
  ('Peru', 'PER', 'B', '🇵🇪'),
  ('Australia', 'AUS', 'B', '🇦🇺'),
  ('Spain', 'ESP', 'C', '🇪🇸'),
  ('Croatia', 'CRO', 'C', '🇭🇷'),
  ('Morocco', 'MAR', 'C', '🇲🇦'),
  ('Belgium', 'BEL', 'C', '🇧🇪'),
  ('Brazil', 'BRA', 'D', '🇧🇷'),
  ('Mexico', 'MEX', 'D', '🇲🇽'),
  ('Ecuador', 'ECU', 'D', '🇪🇨'),
  ('Venezuela', 'VEN', 'D', '🇻🇪'),
  ('France', 'FRA', 'E', '🇫🇷'),
  ('England', 'ENG', 'E', '🏴󠁧󠁢󠁥󠁮󠁧󠁿'),
  ('Serbia', 'SRB', 'E', '🇷🇸'),
  ('South Africa', 'RSA', 'E', '🇿🇦'),
  ('Germany', 'GER', 'F', '🇩🇪'),
  ('Portugal', 'POR', 'F', '🇵🇹'),
  ('Turkey', 'TUR', 'F', '🇹🇷'),
  ('Czech Republic', 'CZE', 'F', '🇨🇿'),
  ('Netherlands', 'NED', 'G', '🇳🇱'),
  ('Colombia', 'COL', 'G', '🇨🇴'),
  ('Uruguay', 'URU', 'G', '🇺🇾'),
  ('Ivory Coast', 'CIV', 'G', '🇨🇮'),
  ('Japan', 'JPN', 'H', '🇯🇵'),
  ('South Korea', 'KOR', 'H', '🇰🇷'),
  ('Saudi Arabia', 'KSA', 'H', '🇸🇦'),
  ('Iran', 'IRN', 'H', '🇮🇷'),
  ('Italy', 'ITA', 'I', '🇮🇹'),
  ('Switzerland', 'SUI', 'I', '🇨🇭'),
  ('Greece', 'GRE', 'I', '🇬🇷'),
  ('Nigeria', 'NGA', 'I', '🇳🇬'),
  ('Poland', 'POL', 'J', '🇵🇱'),
  ('Austria', 'AUT', 'J', '🇦🇹'),
  ('Romania', 'ROU', 'J', '🇷🇴'),
  ('Senegal', 'SEN', 'J', '🇸🇳'),
  ('Canada', 'CAN', 'K', '🇨🇦'),
  ('Algeria', 'ALG', 'K', '🇩🇿'),
  ('Egypt', 'EGY', 'K', '🇪🇬'),
  ('New Zealand', 'NZL', 'K', '🇳🇿'),
  ('Qatar', 'QAT', 'L', '🇶🇦'),
  ('Cameroon', 'CMR', 'L', '🇨🇲'),
  ('Ghana', 'GHA', 'L', '🇬🇭'),
  ('Tunisia', 'TUN', 'L', '🇹🇳');
